### ISSUE TITLE
Callback Component Question

### ISSUE THREAD

**Issue by Singularity222** [elanderson/Angular-Core-IdentityServer#24]
Hey there, I have a question. I've been using this repository as a base for another project I'm working on. However, I have an issue. It seems everything is working fine connecting to the identity server from my Angular app, but after the user logs in and is redirected, the auth service does not seem like it's getting a token back. In identity server I see this is set:

RedirectUris = { $"{configuration["ClientAddress"]}/callback" },

What is this /callback route referring to? I see this blog post:
https://elanderson.net/2017/07/identity-server-usage-from-angular/

It mentions to take a look at the code in Github to see how the callback component works. In the current version of your code however, there is no callback component. Your current version seems to be working fine as well. So what am I missing? What is the replacement for the callback component in the latest version of your app? Any help would be appreciated.

**Comment by elanderson** [comment]
@Singularity222 if you look at the repo in the state it was when that blog post was written then you will see the usage of the callback. Since that post, I have upgraded the OIDC client to use [this](https://github.com/damienbod/angular-auth-oidc-client) package which was built specifically for Angular. You can read about the transition in [this](https://elanderson.net/2017/09/identity-server-changing-angular-openid-connect-clients/) post.

I'm not sure at what point you created the base for your application, but you might want to look at the commits after that point and apply any changes to your local project. After that, if you are still having an issue feel free to reopen and I will try and help out.

**Comment by Singularity222** [comment]
So I'm using the latest version of your code, after you've removed the callback component and switched to the new library. In the latest version of your code however, you still have references to the callback route in identity server even though you removed the component in the blog post you reference. I thought maybe I was missing something considering I couldn't find a callback route configured in the Angular app.

**Comment by elanderson** [comment]
Ah ok, I see. I believe that it is handled by the OIDC client.
